spring:
  cloud:
    gateway:
      routes:
        - id: user-service-private-get
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/users/me
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            - JwtAuthGatewayFilter

        - id: user-service-allow-anonymous-get
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/users/*
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            - name: JwtAuthGatewayFilter
              args:
                allowAnonymous: true

        - id: user-service-private-post
          uri: lb://USER-SERVICE
          predicates:
            - Path=
              /user-service/users/*/follow,
              /user-service/follows/**,
              /user-service/follows/*/accept,
              /user-service/follows/*/reject,
              /user-service/users/me/profile-image,
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            - JwtAuthGatewayFilter

        - id: user-service-private-patch
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/users/me
            - Method=PATCH
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            - JwtAuthGatewayFilter

        - id: user-service-private-delete
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/users/me, /user-service/follows/**, /user-service/users/me/profile-image,
            - Method=DELETE
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            - JwtAuthGatewayFilter

        - id: user-service-public-get
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/users/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

        - id: user-service-public-post
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/users/signup, /user-service/users/emails/send-code, /user-service/users/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

        - id: user-service-public-patch
          uri: lb://USER-SERVICE
          predicates:
            - Path=
            - Method=PATCH
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

        - id: user-service-public-delete
          uri: lb://USER-SERVICE
          predicates:
            - Path=
            - Method=DELETE
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

        - id: post-service-allow-anonymous-get
          uri: lb://POST-SERVICE
          predicates:
            - Path=/post-service/posts/*, /post-service/posts, /post-service/posts/ids, /post-service/posts/*/comments
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/post-service/(?<segment>.*), /$\{segment}
            - name: JwtAuthGatewayFilter
              args:
                allowAnonymous: true


        - id: post-service-private-get
          uri: lb://POST-SERVICE
          predicates:
            - Path=/post-service/posts/**, /post-service/posts
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/post-service/(?<segment>.*), /$\{segment}
            - JwtAuthGatewayFilter

        - id: post-service-private-post
          uri: lb://POST-SERVICE
          predicates:
            - Path=/post-service/posts, /post-service/posts/*/comments, /post-service/posts/*
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/post-service/(?<segment>.*), /$\{segment}
            - JwtAuthGatewayFilter

        - id: post-service-private-delete
          uri: lb://POST-SERVICE
          predicates:
            - Path=/post-service/posts/**, /post-service/posts/comments/*
            - Method=DELETE
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/post-service/(?<segment>.*), /$\{segment}
            - JwtAuthGatewayFilter

        - id: post-service-private-patch
          uri: lb://POST-SERVICE
          predicates:
            - Path=/post-service/posts/comments/*,
            - Method=PATCH
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/post-service/(?<segment>.*), /$\{segment}
            - JwtAuthGatewayFilter

        - id: feed-service-private-get
          uri: lb://FEED-SERVICE
          predicates:
            - Path=/feed-service/feed ,/feed-service/feed/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/feed-service/(?<segment>.*), /$\{segment}
            - JwtAuthGatewayFilter

        - id: post-search-service-public-get
          uri: lb://post-search-service
          predicates:
            - Path=/post-search-service/posts/search
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/post-search-service/(?<segment>.*), /$\{segment}
