server:
  port: 8000

spring:
  config:
    activate:
      on-profile: default
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: user-service-public
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/users/signup, /user-service/users/emails/send-code, /user-service/users/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: user-service-auth
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/users/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            - JwtAuthGatewayFilter
        - id: user-service-patch
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/users/me/**
            - Method=PATCH
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            - JwtAuthGatewayFilter
jwt:
  secret: 9F8xvM1QK5Pj1W7RZyG+2tOQVp3X6LbBgNT9aFovRj0=
  expiration: 3600000