server:
  port: 8000
spring:
  config:
    import:
      - classpath:/users/user-service-routes.yml
    activate:
      on-profile: default
  application:
    name: apigateway-service


jwt:
  secret: 9F8xvM1QK5Pj1W7RZyG+2tOQVp3X6LbBgNT9aFovRj0=
  expiration: 3600000

management:
  endpoints:
    web:
      exposure:
        include: gateway
  endpoint:
    gateway:
      access: read_only